# Generated by Django 6.0.8 on 2026-09-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryproduct_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
