# Generated by Django 6.0.8 on 2026-08-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0063_makerspacemembership_activated_actor_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTenantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_archive_digest', models.CharField(max_length=64)),
                ('source_model_label', models.CharField(max_length=100)),
                ('source_object_id', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=64)),
                ('target_model_label', models.CharField(blank=True, max_length=100)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tenant_references', to='makerspaces.makerspace')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'target_model_label', 'target_object_id'], name='tenant_migr_makersp_c002a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'source_archive_digest', 'source_model_label', 'source_object_id', 'field_name'), name='uniq_external_tenant_reference')],
            },
        ),
    ]
