# Generated by Django 6.0.8 on 2026-09-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_migration', '0009_tenant_dump_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdumpcapture',
            name='money_fingerprint_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
