import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-ink": "rgb(var(--color-accent-ink) / <alpha-value>)",
        "accent-bright": "rgb(var(--color-accent-bright) / <alpha-value>)",
        "on-accent": "rgb(var(--color-on-accent) / <alpha-value>)",
        "on-success": "rgb(var(--color-on-success) / <alpha-value>)",
        "on-warn": "rgb(var(--color-on-warn) / <alpha-value>)",
        "on-info": "rgb(var(--color-on-info) / <alpha-value>)",
        "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-ink": "rgb(var(--color-secondary-ink) / <alpha-value>)",
        ink: "rgb(var(--color-ink) / <alpha-value>)",
        bg: "rgb(var(--color-bg) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        panel: "rgb(var(--color-panel) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        line: "rgb(var(--color-line) / <alpha-value>)",
        outline: "rgb(var(--color-outline) / <alpha-value>)",
        focus: "rgb(var(--color-focus) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-ink": "rgb(var(--color-success-ink) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        warn: "rgb(var(--color-warn) / <alpha-value>)",
        "warn-ink": "rgb(var(--color-warn-ink) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        "info-ink": "rgb(var(--color-info-ink) / <alpha-value>)",
      },
      fontFamily: {
        display: ['"Clash Display"', "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ['"Instrument Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
      },
      boxShadow: {
        soft: "0 1px 2px rgb(var(--shadow-color) / 0.06), 0 6px 16px rgb(var(--shadow-color) / 0.07)",
        "soft-lg": "0 2px 4px rgb(var(--shadow-color) / 0.07), 0 12px 28px rgb(var(--shadow-color) / 0.10)",
        brutal: "0 1px 2px rgb(var(--shadow-color) / 0.06), 0 6px 16px rgb(var(--shadow-color) / 0.07)",
        "brutal-sm": "0 1px 2px rgb(var(--shadow-color) / 0.05), 0 3px 10px rgb(var(--shadow-color) / 0.06)",
        "brutal-lg": "0 2px 4px rgb(var(--shadow-color) / 0.07), 0 12px 28px rgb(var(--shadow-color) / 0.10)",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
      },
      backgroundSize: {
        blueprint: "32px 32px",
      },
    },
  },
  plugins: [],
} satisfies Config;
