# Generated by Django 6.0.8 on 2026-09-03 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookablespace_approval_mode'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookablespace',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='machines.machinetype'),
        ),
    ]
