#!/usr/bin/env bash
# Space Works - Open Source Makerspace Manager first-run setup for self-hosting (macOS / Linux).
# Run it from the project folder:  bash setup.sh
set -euo pipefail
cd "$(dirname "$0")"

COMPOSE=(docker compose -f docker-compose.prod.yml -f docker/compose.build.yml)

say()  { printf '\n\033[1;36m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m%s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# 1. Docker must be installed and running.
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
docker info >/dev/null 2>&1 || die "Docker is installed but not running. Start Docker Desktop, then run this again."
docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is missing. Update Docker Desktop."

# Subshell disables pipefail locally: `head` closing the pipe makes `tr` exit via SIGPIPE,
# which would otherwise abort the script under `set -o pipefail`.
rand_key()   { ( set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-50}" ); }
fernet_key() { head -c 32 /dev/urandom | base64 | tr '+/' '-_'; }

FIRST_RUN=0
if [ -f .env ]; then
  say "Found an existing .env — keeping your settings and secrets."
else
  FIRST_RUN=1
  say "Welcome! Let's set up Space Works. Press Enter to accept the [default]."
  read -r -p "Web address (host name or IP, no http://) [localhost]: " WEBADDR;  WEBADDR="${WEBADDR:-localhost}"
  # Normalize: strip any scheme, path, and port so ALLOWED_HOSTS/CORS are valid.
  WEBHOST="${WEBADDR#*://}"; WEBHOST="${WEBHOST%%/*}"; WEBHOST="${WEBHOST%%:*}"
  [ -n "$WEBHOST" ] || WEBHOST="localhost"
  read -r -p "Name of your makerspace [My Makerspace]: "                   MSNAME;   MSNAME="${MSNAME:-My Makerspace}"
  read -r -p "Admin login username [admin]: "                             ADMINUSER; ADMINUSER="${ADMINUSER:-admin}"
  read -r -p "Admin email [admin@example.com]: "                          ADMINEMAIL; ADMINEMAIL="${ADMINEMAIL:-admin@example.com}"
  read -r -s -p "Admin password (leave blank to auto-generate): "         ADMINPASS; echo
  GEN_PASS=0
  if [ -z "$ADMINPASS" ]; then ADMINPASS="$(rand_key 16)"; GEN_PASS=1; fi
  read -r -p "Stripe secret key (optional; leave blank to skip): " STRIPE_SECRET_KEY
  read -r -s -p "Stripe webhook secret (optional; leave blank to skip): " STRIPE_WEBHOOK_SECRET; echo
  read -r -p "Stripe default currency [usd]: " STRIPE_DEFAULT_CURRENCY; STRIPE_DEFAULT_CURRENCY="${STRIPE_DEFAULT_CURRENCY:-usd}"
  if [ -n "$STRIPE_SECRET_KEY" ] && [ -z "$STRIPE_WEBHOOK_SECRET" ] || [ -z "$STRIPE_SECRET_KEY" ] && [ -n "$STRIPE_WEBHOOK_SECRET" ]; then
    warn "Stripe needs both secrets; leaving payments unconfigured."
    STRIPE_SECRET_KEY=""; STRIPE_WEBHOOK_SECRET=""
  fi

  say "Writing .env (secrets generated automatically)..."
  cat > .env <<EOF
# Generated by setup.sh — keep this file private; it holds your secrets.
POSTGRES_PASSWORD=$(rand_key 32)
MINIO_ROOT_USER=$(rand_key 24)
MINIO_ROOT_PASSWORD=$(rand_key 40)
SECRET_KEY=$(rand_key 50)
API_CLIENT_ENC_KEY=$(fernet_key)
ALLOWED_HOSTS=${WEBHOST},localhost,127.0.0.1,backend
CORS_ALLOWED_ORIGINS=http://${WEBHOST}
# Absolute base for links in outbound email (password reset, invitations). Without it
# those links are emitted as bare paths like "/reset-password?..." and are unclickable.
PUBLIC_APP_BASE_URL=http://${WEBHOST}
HTTP_PORT=80
ENABLE_HTTPS=false
EOF
fi

say "Building and starting the app (first run can take a few minutes)..."
"${COMPOSE[@]}" up -d --build

say "Waiting for the app to be ready..."
ready=0
for _ in $(seq 1 60); do
  if "${COMPOSE[@]}" exec -T backend python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health/readiness/', timeout=3)" >/dev/null 2>&1; then
    ready=1; break
  fi
  sleep 3
done
[ "$ready" = 1 ] || die "The app did not become ready in time. Check logs with: ${COMPOSE[*]} logs backend"

if [ "$FIRST_RUN" = 1 ]; then
  say "Creating your admin account and makerspace..."
  "${COMPOSE[@]}" exec -T backend python manage.py setup_instance \
    --username "$ADMINUSER" --email "$ADMINEMAIL" --password "$ADMINPASS" \
    --makerspace-name "$MSNAME"

  if [ -n "$STRIPE_SECRET_KEY" ]; then
    SETUP_STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
    SETUP_STRIPE_WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET" \
    SETUP_STRIPE_DEFAULT_CURRENCY="$STRIPE_DEFAULT_CURRENCY" \
    SETUP_MAKERSPACE_NAME="$MSNAME" \
    "${COMPOSE[@]}" exec -T \
      -e SETUP_STRIPE_SECRET_KEY -e SETUP_STRIPE_WEBHOOK_SECRET \
      -e SETUP_STRIPE_DEFAULT_CURRENCY -e SETUP_MAKERSPACE_NAME \
      backend python manage.py shell -c '
import os
from django.utils.text import slugify
from apps.makerspaces.models import Makerspace
from apps.payments.models import MakerspacePaymentSettings
makerspace = Makerspace.objects.get(slug=slugify(os.environ["SETUP_MAKERSPACE_NAME"]))
settings = MakerspacePaymentSettings.for_makerspace(makerspace)
settings.set_stripe_secret_key(os.environ["SETUP_STRIPE_SECRET_KEY"])
settings.set_stripe_webhook_secret(os.environ["SETUP_STRIPE_WEBHOOK_SECRET"])
settings.default_currency = os.environ["SETUP_STRIPE_DEFAULT_CURRENCY"]
settings.save()
'
  fi

  read -r -p "Enable automatic production updates from main? [Y/n]: " AUTOUPDATE
  AUTOUPDATE="${AUTOUPDATE:-Y}"
  if [[ "$AUTOUPDATE" =~ ^[Yy]$ ]]; then
    if ! bash scripts/install-auto-update.sh; then
      warn "Could not install the seven-day updater. Run bash scripts/install-auto-update.sh later."
    fi
  else
    if bash scripts/install-auto-update.sh; then
      "${COMPOSE[@]}" exec -T backend python manage.py update_control set-auto off >/dev/null
      warn "Automatic installation is off. The host will still check for releases so Update now works from Platform settings."
    else
      warn "Could not install the seven-day update checker. Run bash scripts/install-auto-update.sh later, then turn automatic updates off in Platform settings."
    fi
  fi

  PORT="$(grep -E '^HTTP_PORT=' .env | cut -d= -f2)"; PORT="${PORT:-80}"
  HOST="$(grep -E '^ALLOWED_HOSTS=' .env | cut -d= -f2 | cut -d, -f1)"; HOST="${HOST:-localhost}"
  SUFFIX=""; [ "$PORT" != "80" ] && SUFFIX=":$PORT"
  say "All done! 🎉"
  echo   "  Public catalog : http://${HOST}${SUFFIX}/"
  echo   "  Staff console  : http://${HOST}${SUFFIX}/admin   (React, username: ${ADMINUSER})"
  echo   "  Control plane  : /control/ on the backend only; not published on the public port"
  [ "$GEN_PASS" = 1 ] && warn "  Generated admin password: ${ADMINPASS}   (save this now)"
  echo
  echo   "Next: log into the React staff console at /admin, add inventory, and turn on 'public inventory' for your makerspace."
else
  say "App started. To create the first admin (only if you haven't yet), run:"
  echo "  ${COMPOSE[*]} exec backend python manage.py setup_instance --username admin --password 'a-strong-password' --makerspace-name 'My Makerspace'"
fi
