# Generated by Django 6.0.8 on 2026-08-09 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_qr_print_batch_item_unique_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'periodic task run',
                'verbose_name_plural': 'periodic task runs',
            },
        ),
    ]
