# Generated by Django 6.0.8 on 2026-09-03 23:56

import apps.operations.models_report_schedules
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_webhook_channel'),
        ('makerspaces', '0070_memberprofile_show_certifications'),
        ('operations', '0008_report_rollups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=80)),
                ('filters', models.JSONField(blank=True, default=dict, validators=[apps.operations.models_report_schedules.validate_schedule_filters])),
                ('grain', models.CharField(default='day', max_length=8)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], default='csv', max_length=8)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=8)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_emails', models.JSONField(blank=True, default=list, validators=[apps.operations.models_report_schedules.validate_recipient_emails])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to='integrations.notificationdestination')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='makerspaces.makerspace')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=8)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='operations.reportschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='report_schedule_due_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['makerspace', '-created_at'], name='report_schedule_ms_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['schedule', '-created_at'], name='report_delivery_sched_idx'),
        ),
    ]
