import base64
import hashlib
import json
import uuid

import pytest
from django.db import connection

from apps.backup.reservation_catalog import IndexComponent, UniqueRule, load_unique_rules
from apps.backup.reservation_keys import (
    COMMITMENT_DOMAIN,
    KEY_VERSION,
    CanonicalComponent,
    fresh_run_salt,
    reservation_commitment,
    reservation_key_v1,
)
from apps.backup.reservation_registry import (
    ReservationMode,
    canonicalizer_for,
    reservation_mode,
)
from apps.backup.postgres_client import server_major
from apps.backup.source_reservations import ReservationCapture, _evaluate_rule
from tests.backup.e7_reservation_test_helpers import CommitmentProbe


pytestmark = pytest.mark.django_db(transaction=True)


def _frame(value):
    return len(value).to_bytes(8, "big") + value


def _rule(index_name):
    return next(item for item in load_unique_rules() if item.index_name == index_name)


@pytest.fixture
def commitment_probe_table():
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS backup_e7_commitment_probe CASCADE")
        cursor.execute(
            'CREATE TABLE backup_e7_commitment_probe ('
            'id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            'left_token text COLLATE "C", right_token text COLLATE "C", '
            'uuid_token uuid, active boolean NOT NULL DEFAULT true)'
        )
    try:
        yield
    finally:
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS backup_e7_commitment_probe CASCADE")


def test_reservation_key_v1_frames_single_and_composite_components_exactly():
    identity = hashlib.sha256(b"constraint").hexdigest()
    single = reservation_key_v1(
        identity,
        [CanonicalComponent("pg_catalog.uuid:uuid", b"uuid-bytes")],
        nulls_not_distinct=False,
    )
    assert single == (
        _frame(KEY_VERSION)
        + _frame(bytes.fromhex(identity))
        + (1).to_bytes(4, "big")
        + _frame(b"pg_catalog.uuid:uuid")
        + b"\x01"
        + _frame(b"uuid-bytes")
    )

    left = reservation_key_v1(
        identity,
        [
            CanonicalComponent("pg_catalog.text:text", b"ab"),
            CanonicalComponent("pg_catalog.text:text", b"c"),
        ],
        nulls_not_distinct=False,
    )
    right = reservation_key_v1(
        identity,
        [
            CanonicalComponent("pg_catalog.text:text", b"a"),
            CanonicalComponent("pg_catalog.text:text", b"bc"),
        ],
        nulls_not_distinct=False,
    )
    assert left != right
    assert left == (
        _frame(KEY_VERSION)
        + _frame(bytes.fromhex(identity))
        + (2).to_bytes(4, "big")
        + _frame(b"pg_catalog.text:text") + b"\x01" + _frame(b"ab")
        + _frame(b"pg_catalog.text:text") + b"\x01" + _frame(b"c")
    )


def test_commitment_domain_formula_fresh_salt_and_manifest_secrecy():
    identity = hashlib.sha256(b"published-rule").hexdigest()
    raw_key = reservation_key_v1(
        identity,
        [CanonicalComponent("pg_catalog.uuid:uuid", b"private-canonical-bytes")],
        nulls_not_distinct=False,
    )
    first_salt, second_salt = fresh_run_salt(), fresh_run_salt()
    assert first_salt != second_salt
    published = reservation_commitment(first_salt, raw_key)
    assert published == hashlib.sha256(
        COMMITMENT_DOMAIN + first_salt + raw_key
    ).hexdigest()
    assert reservation_commitment(second_salt, raw_key) != published

    capture = ReservationCapture(
        run_salt=first_salt,
        registry_digest="a" * 64,
        commitments=({
            "constraint_identity": identity,
            "definition_sha256": "b" * 64,
            "canonicalizer_identity": "c" * 64,
            "key_component_identities": [],
            "component_commitments": [{
                "component_id": str(uuid.uuid4()), "commitments": [published]
            }],
        },),
        broad_fences=(), relationship_fences=(), object_namespace_fences=(),
        sequence_facts=(), rule_proofs=(),
        raw_keys_by_component={"private": ((identity, raw_key),)},
    )
    encoded = json.dumps(capture.manifest_facts(), sort_keys=True)
    assert capture.manifest_facts()["reservation_salt"] == base64.b64encode(
        first_salt
    ).decode("ascii")
    assert "private-canonical-bytes" not in encoded
    assert base64.b64encode(raw_key).decode("ascii") not in encoded
    assert raw_key.hex() not in encoded


def test_postgresql_evaluates_expression_case_fold_and_sql_true_predicate(
    commitment_probe_table,
):
    with connection.cursor() as cursor:
        cursor.execute(
            'CREATE UNIQUE INDEX e7_expression_unique '
            'ON backup_e7_commitment_probe '
            '((lower(left_token) COLLATE "C")) WHERE active IS TRUE'
        )
        cursor.execute(
            "INSERT INTO backup_e7_commitment_probe "
            "(left_token, active) VALUES ('MiXeD', true), ('MiXeD', false)"
        )
        cursor.execute(
            "SELECT pg_catalog.convert_to(lower(left_token)::text, 'UTF8') "
            "FROM backup_e7_commitment_probe WHERE active IS TRUE"
        )
        postgresql_bytes = bytes(cursor.fetchone()[0])
    rule = _rule("e7_expression_unique")
    framed = _evaluate_rule(
        "default", rule, CommitmentProbe.objects.all(), server_major(),
        canonicalize=True,
    )

    assert rule.components[0].expression_sql == "lower(left_token)"
    assert canonicalizer_for(rule.components[0], server_major()).identity == (
        "postgres-deterministic-text-utf8-v1"
    )
    assert rule.predicate_sql
    assert len(framed) == 1
    assert bytes.fromhex(rule.identity) in framed[0]
    assert _frame(postgresql_bytes) in framed[0]
    assert b"MiXeD" not in framed[0]


def test_postgresql_composite_index_order_is_one_unambiguous_commitment_key(
    commitment_probe_table,
):
    with connection.cursor() as cursor:
        cursor.execute(
            "CREATE UNIQUE INDEX e7_composite_unique "
            "ON backup_e7_commitment_probe (left_token, right_token)"
        )
        cursor.execute(
            "INSERT INTO backup_e7_commitment_probe (left_token, right_token) "
            "VALUES ('ab', 'c')"
        )
    rule = _rule("e7_composite_unique")
    first = _evaluate_rule(
        "default", rule, CommitmentProbe.objects.all(), server_major(),
        canonicalize=True,
    )[0]
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM backup_e7_commitment_probe")
        cursor.execute(
            "INSERT INTO backup_e7_commitment_probe (left_token, right_token) "
            "VALUES ('a', 'bc')"
        )
    second = _evaluate_rule(
        "default", rule, CommitmentProbe.objects.all(), server_major(),
        canonicalize=True,
    )[0]

    assert [item.source_column for item in rule.components] == [
        "left_token", "right_token"
    ]
    assert first != second
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX e7_composite_unique")
        cursor.execute(
            "CREATE UNIQUE INDEX e7_composite_unique "
            "ON backup_e7_commitment_probe (right_token, left_token)"
        )
    reversed_rule = _rule("e7_composite_unique")
    assert [item.source_column for item in reversed_rule.components] == [
        "right_token", "left_token"
    ]
    assert reversed_rule.identity != rule.identity


def test_null_distinct_skips_and_nulls_not_distinct_frames_null(
    commitment_probe_table,
):
    with connection.cursor() as cursor:
        cursor.execute(
            "CREATE UNIQUE INDEX e7_null_distinct "
            "ON backup_e7_commitment_probe (uuid_token)"
        )
        cursor.execute(
            "INSERT INTO backup_e7_commitment_probe (uuid_token) VALUES (NULL)"
        )
    distinct = _rule("e7_null_distinct")
    assert _evaluate_rule(
        "default", distinct, CommitmentProbe.objects.all(), server_major(),
        canonicalize=True,
    ) == [None]

    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX e7_null_distinct")
        cursor.execute(
            "CREATE UNIQUE INDEX e7_nulls_not_distinct "
            "ON backup_e7_commitment_probe (uuid_token) NULLS NOT DISTINCT"
        )
    not_distinct = _rule("e7_nulls_not_distinct")
    framed = _evaluate_rule(
        "default", not_distinct, CommitmentProbe.objects.all(), server_major(),
        canonicalize=True,
    )
    assert not_distinct.nulls_not_distinct is True
    assert len(framed) == 1 and framed[0] is not None
    assert framed[0].endswith(_frame(not_distinct.components[0].type_identity.encode()) + b"\x00")


@pytest.mark.parametrize(
    ("type_identity", "operator_class", "expected"),
    (
        ("pg_catalog.int8:bigint", "pg_catalog.int8_ops", "postgres-int-send-v1"),
        ("pg_catalog.uuid:uuid", "pg_catalog.uuid_ops", "postgres-uuid-send-v1"),
        ("pg_catalog.text:text", "pg_catalog.text_ops", "postgres-deterministic-text-utf8-v1"),
        ("pg_catalog.bpchar:character(8)", "pg_catalog.bpchar_ops", "postgres-bpchar-trim-utf8-v1"),
    ),
)
def test_supported_postgresql_canonicalizers(type_identity, operator_class, expected):
    component = IndexComponent(
        1, "probe", "probe", type_identity, operator_class,
        "pg_catalog.C", "c", True, "C", "", "",
    )
    assert canonicalizer_for(component, 16).identity == expected


def test_unproved_opclass_falls_back_to_broad_fence():
    component = IndexComponent(
        1, "public_token", "public_token", "pg_catalog.uuid:uuid",
        "public.unproved_uuid_ops", "", "", True, "", "", "",
    )
    rule = UniqueRule(
        "public", "hardware_requests_hardwarerequest", "unproved", "index",
        "", "", False, False, False, False, (component,),
    )
    assert reservation_mode(rule, 16) is ReservationMode.BROAD_FENCE
