import uuid

import pytest
from django.db import connection

from apps.backup.models import B1ReservationEntry
from apps.backup.postgres_client import server_major
from apps.backup.reservation_catalog import load_unique_rules
from apps.backup.reservation_enforcement import install_reservation_entry
from apps.backup.reservation_keys import (
    CanonicalComponent,
    fresh_run_salt,
    reservation_commitment,
    reservation_key_v1,
)
from apps.backup.reservation_registry import (
    canonicalizer_identity,
    component_canonicalizer_identities,
)
from tests.backup.e7_reservation_test_helpers import (
    CommitmentProbe,
    assert_database_rejects,
    persist_restore_state,
)


pytestmark = pytest.mark.django_db(transaction=True)


@pytest.fixture
def commitment_probe_table():
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS backup_e7_commitment_probe CASCADE")
        cursor.execute(
            "CREATE TABLE backup_e7_commitment_probe ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "left_token text, right_token text, uuid_token uuid, "
            "active boolean NOT NULL DEFAULT true)"
        )
        cursor.execute(
            "CREATE UNIQUE INDEX e7_database_commitment "
            "ON backup_e7_commitment_probe (uuid_token)"
        )
    try:
        yield
    finally:
        with connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS backup_e7_commitment_probe CASCADE")


def test_database_commitment_trigger_uses_the_reproduced_uuid_rule(
    commitment_probe_table,
):
    reserved = uuid.uuid4()
    component_id = uuid.uuid4()
    with connection.cursor() as cursor:
        cursor.execute("SELECT pg_catalog.uuid_send(%s::uuid)", [str(reserved)])
        canonical = bytes(cursor.fetchone()[0])
    rule = next(
        item for item in load_unique_rules()
        if item.index_name == "e7_database_commitment"
    )
    salt = fresh_run_salt()
    framed = reservation_key_v1(
        rule.identity,
        [CanonicalComponent(rule.components[0].type_identity, canonical)],
        nulls_not_distinct=False,
    )
    fact = {
        "constraint_identity": rule.identity,
        "definition_sha256": rule.definition_sha256,
        "canonicalizer_identity": canonicalizer_identity(rule, server_major()),
        "key_component_identities": list(
            component_canonicalizer_identities(rule, server_major())
        ),
        "component_commitments": [{
            "component_id": str(component_id),
            "commitments": [reservation_commitment(salt, framed)],
        }],
    }
    operation_id, state_component_id = persist_restore_state({
        "component_ids": [str(component_id)]
    })
    assert state_component_id == component_id
    install_reservation_entry(
        operation_id=operation_id,
        component_id=component_id,
        kind=B1ReservationEntry.Kind.COMMITMENT,
        fact=fact,
        reservation_salt=salt,
    )

    assert_database_rejects(lambda: CommitmentProbe.objects.create(
        uuid_token=reserved
    ))
    assert CommitmentProbe.objects.create(uuid_token=uuid.uuid4()).pk is not None
