import json
import uuid

import pytest
from django.db import connection, connections

from apps.backup.main_projection import _install_sequence_high_water
from apps.backup.main_projection_verification import (
    _apply_expected_sequence_high_water,
    _sequence_ledger,
)
from apps.backup.models import B1ReservationEntry
from apps.backup.outer_reservation_validation import _validate_sequences
from apps.backup.postgres_client import server_major
from apps.backup.reservation_catalog import load_unique_rules
from apps.backup.reservation_registry import ReservationMode
from apps.backup.source_fences import broad_unique_fence
from apps.backup.source_reservations import _bind_sequence_rules, _effective_mode
from apps.backup.source_sequence_reservations import sequence_facts
from tests.backup.e7_reservation_test_helpers import (
    assert_database_rejects,
    digest,
    persist_active_reservation,
)


pytestmark = pytest.mark.django_db(transaction=True)


SEQUENCE_TABLE = "backup_e7_sequence_probe"
NUMERIC_TABLE = "backup_e7_numeric_probe"


@pytest.fixture
def numeric_identity_tables():
    with connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE IF EXISTS {SEQUENCE_TABLE} CASCADE")
        cursor.execute(f"DROP TABLE IF EXISTS {NUMERIC_TABLE} CASCADE")
        cursor.execute(
            f"CREATE TABLE {SEQUENCE_TABLE} ("
            "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "owner text NOT NULL)"
        )
        cursor.execute(
            f"CREATE TABLE {NUMERIC_TABLE} (id bigint PRIMARY KEY, owner text NOT NULL)"
        )
    try:
        yield
    finally:
        with connection.cursor() as cursor:
            cursor.execute(f"DROP TABLE IF EXISTS {SEQUENCE_TABLE} CASCADE")
            cursor.execute(f"DROP TABLE IF EXISTS {NUMERIC_TABLE} CASCADE")


def _sequence_fact():
    return next(item for item in sequence_facts("default") if item["table"] == SEQUENCE_TABLE)


def test_sequence_high_water_is_computed_before_slice_rows_leave_the_main(
    numeric_identity_tables,
):
    with connection.cursor() as cursor:
        cursor.execute(
            f"INSERT INTO {SEQUENCE_TABLE} (owner) VALUES ('readable-main') RETURNING id"
        )
        main_id = cursor.fetchone()[0]
        cursor.execute(
            f"INSERT INTO {SEQUENCE_TABLE} (id, owner) VALUES "
            "(900, 'opaque-slice-one'), (950, 'opaque-slice-two')"
        )
    fact = _sequence_fact()
    assert fact["captured_last_value"] < 900
    assert fact["installed_last_value"] == 950
    assert fact["next_generated_value"] == 951

    with connection.cursor() as cursor:
        cursor.execute(f"DELETE FROM {SEQUENCE_TABLE} WHERE owner LIKE 'opaque-slice-%'")
    _install_sequence_high_water("default", (fact,))
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT id FROM {SEQUENCE_TABLE} ORDER BY id")
        assert [row[0] for row in cursor.fetchall()] == [main_id]
        cursor.execute(
            f"INSERT INTO {SEQUENCE_TABLE} (owner) VALUES ('serving-write') RETURNING id"
        )
        assert cursor.fetchone()[0] == 951


def test_empty_sequence_expectation_uses_the_installed_high_water_state(
    numeric_identity_tables,
):
    fact = _sequence_fact()
    assert fact["captured_is_called"] is False
    assert fact["installed_is_called"] is True
    ledger = _sequence_ledger("default")

    _apply_expected_sequence_high_water(ledger, (fact,))

    assert ledger[fact["sequence"]][-2:] == [
        fact["installed_last_value"], True
    ]


def test_sequence_manifest_fact_is_high_water_only_not_a_row_value_ledger(
    numeric_identity_tables,
):
    with connection.cursor() as cursor:
        cursor.execute(
            f"INSERT INTO {SEQUENCE_TABLE} (id, owner) VALUES "
            "(41, 'private-row-marker-one'), (73, 'private-row-marker-two')"
        )
    fact = _bind_sequence_rules((_sequence_fact(),), load_unique_rules())[0]
    encoded = json.dumps(fact, sort_keys=True)

    assert fact["installed_last_value"] == 73
    assert fact["next_generated_value"] == 74
    assert "private-row-marker" not in encoded
    assert set(fact) == {
        "schema", "sequence", "table", "column", "type_identity",
        "increment", "start", "minimum", "maximum", "cycle", "cache",
        "captured_last_value", "captured_is_called", "installed_last_value",
        "installed_is_called", "next_generated_value",
        "constraint_identity", "definition_sha256",
    }

    invalid = dict(fact, cache=0)
    with pytest.raises(ValueError):
        _validate_sequences([invalid])

    invalid = dict(fact, next_generated_value=fact["installed_last_value"])
    with pytest.raises(ValueError):
        _validate_sequences([invalid])


def test_non_sequence_numeric_identity_gets_a_broad_insert_fence(
    numeric_identity_tables,
):
    rule = next(
        item for item in load_unique_rules()
        if item.table == NUMERIC_TABLE and item.primary
    )
    assert _effective_mode(
        rule, "default", server_major()
    ) is ReservationMode.BROAD_FENCE
    fence = broad_unique_fence(
        rule, [{"component_id": str(uuid.uuid4()), "count": 2}]
    )
    assert fence["operations"] == ["insert", "update"]
    assert "commitments" not in fence
    assert "values" not in fence


def test_database_rejects_explicit_write_inside_a_reserved_numeric_range(
    numeric_identity_tables,
):
    component_id = uuid.uuid4()
    fact = {
        "version": "b1-numeric-range-reservation-v1",
        "registry_identity": digest(f"{SEQUENCE_TABLE}.id"),
        "schema": "public",
        "table": SEQUENCE_TABLE,
        "column": "id",
        "lower_inclusive": 900,
        "upper_inclusive": 900,
        "operations": ["insert"],
        "component_ids": [str(component_id)],
        "definition_sha256": digest("e7-sequence-range-900"),
    }
    persist_active_reservation(fact, B1ReservationEntry.Kind.NUMERIC_RANGE)

    def claim_reserved_slot():
        with connections["default"].cursor() as cursor:
            cursor.execute(
                f"INSERT INTO {SEQUENCE_TABLE} (id, owner) VALUES (900, 'collision')"
            )

    assert_database_rejects(claim_reserved_slot)
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT count(*) FROM {SEQUENCE_TABLE} WHERE id = 900")
        assert cursor.fetchone()[0] == 0
