# Generated by Django 6.0.8 on 2026-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
