# Generated by Django 6.0.8 on 2026-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0009_qrscanevent_qrscan_ms_qrcode_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='target_type',
            field=models.CharField(choices=[('box', 'Box'), ('product', 'Product'), ('asset', 'Asset'), ('member_card', 'Member card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qrscanevent',
            name='context',
            field=models.CharField(choices=[('issue', 'Issue'), ('return', 'Return'), ('inventory_check', 'Inventory Check'), ('reassignment', 'Reassignment'), ('scanner_lookup', 'Scanner Lookup'), ('member_lookup', 'Member card lookup')], max_length=32),
        ),
    ]
