# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0004_evidencephoto_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceUploadFinalization",
            fields=[
                (
                    "evidence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="upload_finalization",
                        serialize=False,
                        to="evidence.evidencephoto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("promoting", "Promoting"),
                            ("finalized", "Finalized"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("quota_charged", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
