# Generated by Django 6.0.8 on 2026-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0053_convert_guest_admin_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makerspacemembership',
            name='role',
            field=models.CharField(choices=[('space_manager', 'Space Manager'), ('inventory_manager', 'Inventory Manager'), ('print_manager', 'Print Manager'), ('machine_manager', 'Machine Manager'), ('custom', 'Custom')], default='space_manager', max_length=32),
        ),
        migrations.AlterField(
            model_name='makerspacerole',
            name='legacy_role',
            field=models.CharField(blank=True, choices=[('space_manager', 'Space Manager'), ('inventory_manager', 'Inventory Manager'), ('print_manager', 'Print Manager'), ('machine_manager', 'Machine Manager')], max_length=32, null=True),
        ),
    ]
