# Generated by Django 6.0.8 on 2026-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0054_alter_makerspacemembership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='discord_webhook_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
