# Generated by Django 6.0.8 on 2026-08-10 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0057_backfill_phase3_module_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False, help_text='Whether other members of this makerspace can see this profile.')),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_key', models.CharField(blank=True, default='', max_length=500)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('github_username', models.CharField(blank=True, default='', max_length=39)),
                ('github_contributions', models.PositiveIntegerField(blank=True, null=True)),
                ('github_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='makerspaces.makerspacemembership')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image_key', models.CharField(blank=True, default='', max_length=500)),
                ('links', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='makerspaces.memberprofile')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['is_visible'], name='memberprofile_visible_idx'),
        ),
    ]
