# Generated by Django 6.0.8 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makerspaces", "0058_memberprofile_memberproject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="show_attended_events",
            field=models.BooleanField(
                default=False,
                help_text="Whether to publish recently attended events on this member profile.",
            ),
        ),
    ]
