# Generated by Django 6.0.8 on 2026-08-15 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Deliberately no walk-in ``can_refer`` backfill: existing values may be an explicit
# staff grant. The creation service now makes every new walk-in non-referring.


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0061_makerspace_archive_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspacemembership',
            name='witnessed_actor_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='witnessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnessed_waiver_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='witnessed_waiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnessed_by_memberships', to='makerspaces.makerspacewaiver'),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='witnessed_waiver_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='makerspacemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('witnessed_actor_snapshot__isnull', True), ('witnessed_at__isnull', True), ('witnessed_by__isnull', True), ('witnessed_waiver__isnull', True), ('witnessed_waiver_version__isnull', True)), models.Q(('witnessed_at__isnull', False), ('witnessed_waiver__isnull', False), ('witnessed_waiver_version__isnull', False), models.Q(('witnessed_by__isnull', False), ('witnessed_actor_snapshot__isnull', False), _connector='OR')), _connector='OR'), name='membership_witnessed_waiver_all_or_none'),
        ),
    ]
