# Generated by Django 6.0.8 on 2026-08-15 22:27

import apps.makerspaces.provenance
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0062_makerspacemembership_witnessed_actor_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspacemembership',
            name='activated_actor_snapshot',
            field=models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot]),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='revoked_actor_snapshot',
            field=models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot]),
        ),
        migrations.AddField(
            model_name='makerspacemembership',
            name='verified_actor_snapshot',
            field=models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot]),
        ),
        migrations.CreateModel(
            name='ImportedUserReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user_id', models.CharField(max_length=255)),
                ('source_username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_user_reconciliations', to='makerspaces.makerspace')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_identity_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'source_user_id'), name='uniq_import_reconciliation_source_user'), models.CheckConstraint(condition=models.Q(('source_user_id', ''), _negated=True), name='import_reconciliation_source_user_present')],
            },
        ),
        migrations.CreateModel(
            name='PendingImportedMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('archived_role_label', models.CharField(blank=True, max_length=255)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('can_refer', models.BooleanField(default=True)),
                ('can_verify', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_actor_snapshot', models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot])),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_actor_snapshot', models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot])),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_actor_snapshot', models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot])),
                ('revocation_reason', models.TextField(blank=True)),
                ('waiver_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_version_accepted', models.CharField(blank=True, max_length=64, null=True)),
                ('witnessed_waiver_version', models.CharField(blank=True, max_length=64, null=True)),
                ('witnessed_actor_snapshot', models.JSONField(blank=True, null=True, validators=[apps.makerspaces.provenance.validate_actor_snapshot])),
                ('witnessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('source_membership_id', models.CharField(max_length=255)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('unresolved_reason', models.CharField(blank=True, max_length=64)),
                ('accepted_waiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_imported_acceptances', to='makerspaces.makerspacewaiver')),
                ('adopted_membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_adoption', to='makerspaces.makerspacemembership')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_imported_memberships', to='makerspaces.makerspace')),
                ('witnessed_waiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_imported_witnessed_acceptances', to='makerspaces.makerspacewaiver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('makerspace'), django.db.models.functions.text.Lower('email'), name='uniq_pending_import_email_ci'), models.UniqueConstraint(fields=('makerspace', 'source_membership_id'), name='uniq_pending_import_source_membership'), models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('source_membership_id', ''), _negated=True)), name='pending_import_identity_present'), models.CheckConstraint(condition=models.Q(models.Q(('accepted_waiver__isnull', True), ('waiver_accepted_at__isnull', True), ('waiver_version_accepted__isnull', True)), models.Q(('accepted_waiver__isnull', False), ('waiver_accepted_at__isnull', False), ('waiver_version_accepted__isnull', False)), _connector='OR'), name='pending_import_self_waiver_all_or_none'), models.CheckConstraint(condition=models.Q(models.Q(('witnessed_actor_snapshot__isnull', True), ('witnessed_at__isnull', True), ('witnessed_waiver__isnull', True), ('witnessed_waiver_version__isnull', True)), models.Q(('witnessed_actor_snapshot__isnull', False), ('witnessed_at__isnull', False), ('witnessed_waiver__isnull', False), ('witnessed_waiver_version__isnull', False)), _connector='OR'), name='pending_import_witnessed_waiver_all_or_none'), models.CheckConstraint(condition=models.Q(models.Q(('adopted_at__isnull', True), ('adopted_membership__isnull', True)), models.Q(('adopted_at__isnull', False), ('adopted_membership__isnull', False), ('unresolved_reason', '')), _connector='OR'), name='pending_import_terminal_state_consistent')],
            },
        ),
    ]
