# Generated by Django 6.0.8 on 2026-09-03 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0067_reconcile_anonymous_requests_with_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveIntegerField()),
                ('printed_name', models.TextField(blank=True, default='')),
                ('photo_object_key', models.CharField(blank=True, default='', max_length=300)),
                ('photo_content_type', models.CharField(blank=True, default='', max_length=64)),
                ('photo_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('photo_consent_at', models.DateTimeField(blank=True, null=True)),
                ('photo_consent_version', models.CharField(blank=True, default='', max_length=32)),
                ('template_version_at_issue', models.PositiveIntegerField(default=1)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_cards', to='makerspaces.makerspace')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_card', to='makerspaces.makerspacemembership')),
            ],
            options={
                'ordering': ['makerspace_id', 'card_number'],
                'indexes': [models.Index(fields=['makerspace', 'revoked_at'], name='membercard_ms_revoked_idx')],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'card_number'), name='uniq_member_card_number'), models.CheckConstraint(condition=models.Q(models.Q(('photo_consent_at__isnull', True), ('photo_consent_version', ''), ('photo_content_type', ''), ('photo_object_key', ''), ('photo_size_bytes__isnull', True)), models.Q(('photo_consent_at__isnull', False), ('photo_size_bytes__isnull', False), models.Q(('photo_object_key', ''), _negated=True), models.Q(('photo_content_type', ''), _negated=True), models.Q(('photo_consent_version', ''), _negated=True)), _connector='OR'), name='member_card_photo_all_or_nothing')],
            },
        ),
    ]
