# Generated by Django 6.0.8 on 2026-09-03 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0070_memberprofile_show_certifications'),
        ('payments', '0014_refund_and_loan_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='lapsed_members_cannot_borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom_days', 'Custom number of days')], max_length=16)),
                ('custom_days', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_membership_terms', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='makerspaces.makerspacemembership')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='makerspaces.membershipplan')),
                ('renewal_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_membership_terms', to='payments.payment')),
            ],
            options={
                'ordering': ['-starts_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('email', models.TextField(blank=True, default='')),
                ('phone', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_invitation_requests', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_requests', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['makerspace', 'status', 'created_at'], name='invitationreq_ms_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('makerspace', 'name'), name='uniq_membership_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='membership_plan_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_days__gt', 0), ('interval', 'custom_days')), models.Q(models.Q(('interval', 'custom_days'), _negated=True), ('custom_days__isnull', True)), _connector='OR'), name='membership_plan_custom_days_matches_interval'),
        ),
        migrations.AddIndex(
            model_name='membershipterm',
            index=models.Index(fields=['status', 'ends_at'], name='membershipterm_status_ends_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipterm',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='membership_term_ends_after_start'),
        ),
    ]
