# Generated by Django 6.0.8 on 2026-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_retire_guest_admin_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('space_manager', 'Space Manager'), ('requester', 'Requester')], default='requester', max_length=32),
        ),
    ]
