# Generated by Django 6.0.8 on 2026-08-08 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OidcProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('issuer', models.CharField(max_length=255, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('jwks_url', models.CharField(max_length=255, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('client_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('allow_auto_link', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OIDC provider',
                'verbose_name_plural': 'OIDC providers',
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='socialloginnonce',
            name='provider',
            field=models.CharField(max_length=64),
        ),
    ]
