# Generated by Django 6.0.8 on 2026-08-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_oidc_provider'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('link', 'Link a phone number'), ('login', 'Sign in with a phone number')], max_length=16)),
                ('phone_e164', models.CharField(max_length=20)),
                ('code_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone_e164',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_e164', ''), _negated=True), fields=('phone_e164',), name='uniq_nonempty_phone_e164'),
        ),
        migrations.AddField(
            model_name='phoneverificationchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['user', 'phone_e164', 'expires_at'], name='accounts_ph_user_id_293128_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(condition=models.Q(('consumed_at__isnull', True)), fields=['purpose', 'phone_e164'], name='phone_challenge_active_idx'),
        ),
    ]
