# Generated by Django 6.0.8 on 2026-08-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_phoneverificationchallenge_user_phone_e164_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLoginMethods',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('password_enabled', models.BooleanField(default=True, help_text='Username/email and password sign-in, for staff and members alike.')),
                ('social_enabled', models.BooleanField(default=True, help_text='Sign-in through an identity provider — the built-in Google and Apple providers and every configured OIDC provider. They share one endpoint, so they share one switch.')),
                ('phone_enabled', models.BooleanField(default=True, help_text='Sign-in with an SMS code to a verified number.')),
                ('self_registration_enabled', models.BooleanField(default=True, help_text='Whether anyone may create their own member account. With this off, staff add people from the console.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform login methods',
                'verbose_name_plural': 'Platform login methods',
            },
        ),
    ]
