# Generated by Django 6.0.8 on 2026-08-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_platformloginmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
