# Generated by Django 6.0.8 on 2026-08-15 21:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_backfill_is_walk_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_normalized', models.CharField(max_length=254)),
                ('email_fingerprint', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('digest_is_live', models.BooleanField(default=False)),
                ('credential_fingerprint', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('delivering', 'Delivering'), ('issued', 'Issued'), ('consumed', 'Consumed'), ('discarded', 'Discarded'), ('undeliverable', 'Undeliverable'), ('delivery_unknown', 'Delivery unknown')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_owner', models.CharField(blank=True, max_length=128)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('requested_at', models.DateTimeField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_envelopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'requested_at'], name='accounts_pa_status_f2c2c3_idx'), models.Index(fields=['status', 'claim_expires_at'], name='accounts_pa_status_027649_idx'), models.Index(fields=['terminal_at'], name='accounts_pa_termina_2e2508_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email_normalized'), name='uniq_password_reset_email_ci')],
            },
        ),
    ]
