# Generated by Django 6.0.8 on 2026-08-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_memberclaimcode_absolute_expires_at"),
        ("makerspaces", "0061_makerspace_archive_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcBrowserAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=64)),
                ("state_digest", models.CharField(max_length=64, unique=True)),
                ("nonce_digest", models.CharField(max_length=64, unique=True)),
                ("code_verifier", models.CharField(max_length=128)),
                ("redirect_uri", models.CharField(max_length=2048)),
                ("origin", models.CharField(max_length=512)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("intended_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="oidc_browser_attempts", to="makerspaces.makerspacemembership")),
                ("intended_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="oidc_browser_attempts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at", "consumed_at"], name="oidc_attempt_use_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("intended_membership__isnull", True), ("intended_user__isnull", True)), models.Q(("intended_membership__isnull", False), ("intended_user__isnull", False)), _connector="OR"), name="oidc_attempt_binding_pair")],
            },
        ),
    ]
