# Generated by Django 5.1.15 on 2026-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_platformpushsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=8),
        ),
    ]
