# Generated by Django 6.0.8 on 2026-08-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_email_log_skipped_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOtpSmsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('twilio', 'Twilio')], default='twilio', max_length=32)),
                ('account_sid', models.CharField(blank=True, max_length=255)),
                ('auth_token', models.CharField(blank=True, max_length=512)),
                ('from_number', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
