# Generated by Django 6.0.8 on 2026-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_dailyotpsmscounter_platformsmssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotificationcounter',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('native_push', 'Native push')], max_length=16),
        ),
    ]
