# Generated by Django 6.0.8 on 2026-08-08 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_discord_webhook_and_channel_status'),
        ('makerspaces', '0056_backfill_chat_channel_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('hardware_requests', 'Hardware requests'), ('printing', 'Printing'), ('events', 'Events'), ('bookings', 'Bookings'), ('maintenance', 'Maintenance'), ('members', 'Members')], max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('role', 'Role'), ('requester', 'Requester'), ('members', 'All members'), ('user', 'Named user')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_recipients_created', to=settings.AUTH_USER_MODEL)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='makerspaces.makerspace')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='makerspaces.makerspacerole')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['makerspace__name', 'feature', 'event', 'kind'],
                'indexes': [models.Index(fields=['makerspace', 'feature', 'event'], name='integration_makersp_55e594_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'role'), ('role__isnull', False), ('user__isnull', True)), models.Q(('kind', 'user'), ('role__isnull', True), ('user__isnull', False)), models.Q(('kind__in', ('requester', 'members')), ('role__isnull', True), ('user__isnull', True)), _connector='OR'), name='notification_recipient_kind_matches_target'), models.UniqueConstraint(condition=models.Q(('kind__in', ('requester', 'members'))), fields=('makerspace', 'feature', 'event', 'kind'), name='uniq_notification_recipient_special'), models.UniqueConstraint(condition=models.Q(('role__isnull', False)), fields=('makerspace', 'feature', 'event', 'role'), name='uniq_notification_recipient_role'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('makerspace', 'feature', 'event', 'user'), name='uniq_notification_recipient_user')],
            },
        ),
    ]
