# Generated by Django 6.0.8 on 2026-08-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_notificationrecipient'),
        ('inventory', '0009_inventoryproduct_image_key'),
        ('machines', '0020_backfill_role_machine_scope'),
        ('makerspaces', '0056_backfill_chat_channel_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='destination_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='NotificationDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord')], max_length=16)),
                ('label', models.CharField(max_length=80)),
                ('webhook_url', models.TextField(blank=True, default='')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_destinations', to='makerspaces.makerspace')),
            ],
            options={
                'ordering': ['makerspace_id', 'channel', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DestinationMachineTypeScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_destination_scopes', to='machines.machinetype')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_type_scopes', to='integrations.notificationdestination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationMachineScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_destination_scopes', to='machines.machine')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_scopes', to='integrations.notificationdestination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationCategoryScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_destination_scopes', to='inventory.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scopes', to='integrations.notificationdestination')),
            ],
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='integrations.notificationdestination'),
        ),
        migrations.AddIndex(
            model_name='notificationdestination',
            index=models.Index(fields=['makerspace', 'channel', 'is_active'], name='integration_makersp_b1c3d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdestination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel__in', ['slack', 'mattermost', 'discord']), ('telegram_chat_id', ''), models.Q(('webhook_url', ''), _negated=True)), models.Q(('channel', 'telegram'), ('webhook_url', ''), models.Q(('telegram_chat_id', ''), _negated=True)), _connector='OR'), name='notification_destination_credential_matches_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationdestination',
            constraint=models.UniqueConstraint(fields=('makerspace', 'channel', 'label'), name='uniq_notification_destination_label'),
        ),
        migrations.AddConstraint(
            model_name='destinationmachinetypescope',
            constraint=models.UniqueConstraint(fields=('destination', 'machine_type'), name='uniq_destination_machine_type_scope'),
        ),
        migrations.AddConstraint(
            model_name='destinationmachinescope',
            constraint=models.UniqueConstraint(fields=('destination', 'machine'), name='uniq_destination_machine_scope'),
        ),
        migrations.AddConstraint(
            model_name='destinationcategoryscope',
            constraint=models.UniqueConstraint(fields=('destination', 'category'), name='uniq_destination_category_scope'),
        ),
    ]
