# Generated by Django 6.0.8 on 2026-08-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_backfill_notification_destinations'),
        ('makerspaces', '0056_backfill_chat_channel_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='stream',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('printing', 'Printing'), ('events', 'Events'), ('bookings', 'Bookings'), ('maintenance', 'Maintenance'), ('membership', 'Membership')], max_length=16),
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('hardware_requests', 'Hardware requests'), ('printing', 'Printing'), ('events', 'Events'), ('bookings', 'Bookings'), ('maintenance', 'Maintenance'), ('members', 'Members')], max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('text_body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_templates', to='makerspaces.makerspace')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['makerspace_id', 'feature', 'event'],
                'constraints': [models.UniqueConstraint(fields=('makerspace', 'feature', 'event'), name='uniq_chat_template_per_event')],
            },
        ),
    ]
