# Generated by Django 6.0.8 on 2026-08-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_alter_emailtemplate_stream_chattemplate'),
        ('inventory', '0009_inventoryproduct_image_key'),
        ('machines', '0020_backfill_role_machine_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientCategoryScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_scopes', to='inventory.category')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scopes', to='integrations.notificationrecipient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'category'), name='uniq_recipient_category_scope')],
            },
        ),
        migrations.CreateModel(
            name='RecipientMachineScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_scopes', to='machines.machine')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_scopes', to='integrations.notificationrecipient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'machine'), name='uniq_recipient_machine_scope')],
            },
        ),
        migrations.CreateModel(
            name='RecipientMachineTypeScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient_scopes', to='machines.machinetype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_type_scopes', to='integrations.notificationrecipient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'machine_type'), name='uniq_recipient_machine_type_scope')],
            },
        ),
    ]
