# Generated by Django 6.0.8 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0023_recipientcategoryscope_recipientmachinescope_and_more"),
        ("machines", "0020_backfill_role_machine_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineTypeEmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("printing", "Printing"),
                            ("events", "Events"),
                            ("bookings", "Bookings"),
                            ("maintenance", "Maintenance"),
                            ("membership", "Membership"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("requester", "Requester"), ("staff", "Staff")],
                        max_length=16,
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("subject", models.CharField(max_length=200)),
                ("text_body", models.TextField()),
                ("html_body", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="machines.machinetype",
                    ),
                ),
                (
                    "makerspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_type_email_templates",
                        to="makerspaces.makerspace",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "makerspace__name",
                    "machine_type__name",
                    "stream",
                    "audience",
                    "key",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "makerspace",
                            "machine_type",
                            "stream",
                            "audience",
                            "key",
                        ),
                        name="uniq_type_email_template_per_space",
                    )
                ],
            },
        )
    ]
