# Generated by Django 6.0.8 on 2026-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_machinetypeemailtemplate'),
        ('makerspaces', '0067_reconcile_anonymous_requests_with_membership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdestination',
            name='notification_destination_credential_matches_channel',
        ),
        migrations.AddField(
            model_name='notificationdestination',
            name='signing_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dailynotificationcounter',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('webhook', 'Signed webhook'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdeliverylog',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('webhook', 'Signed webhook'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationdestination',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('webhook', 'Signed webhook')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('mattermost', 'Mattermost'), ('discord', 'Discord'), ('webhook', 'Signed webhook'), ('native_push', 'Native push')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='notificationdestination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel__in', ['slack', 'mattermost', 'discord', 'webhook']), ('telegram_chat_id', ''), models.Q(('webhook_url', ''), _negated=True)), models.Q(('channel', 'telegram'), ('webhook_url', ''), models.Q(('telegram_chat_id', ''), _negated=True)), _connector='OR'), name='notification_destination_credential_matches_channel'),
        ),
    ]
