# Generated by Django 6.0.8 on 2026-08-09 20:04

from django.conf import settings
from django.db import migrations, models


def copy_stripe_ids_into_the_generic_columns(apps, schema_editor):
    """Mirror existing Stripe checkout ids into the provider-agnostic columns.

    The `provider` default already fills every existing row with "stripe", but the new
    generic columns would stay NULL, so a live checkout raised before this migration
    would be invisible to the provider-agnostic expire and settle paths -- a member
    could still pay a link that staff had already reconciled offline.

    Only ever writes the new columns. The `stripe_*` columns are read-only historic
    from here on, and Payment rows are immutable once terminal, so rewriting them would
    be both wrong and refused by the trigger.
    """
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(stripe_checkout_session_id__isnull=False).update(
        external_order_id=models.F("stripe_checkout_session_id")
    )
    Payment.objects.filter(stripe_payment_intent_id__isnull=False).update(
        external_payment_id=models.F("stripe_payment_intent_id")
    )
    Payment.objects.exclude(stripe_checkout_url="").update(
        checkout_url=models.F("stripe_checkout_url")
    )


def clear_the_generic_columns(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.update(external_order_id=None, external_payment_id=None, checkout_url="")


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0057_backfill_phase3_module_keys'),
        ('payments', '0009_payment_online_rail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processedstripeevent',
            name='stripe_event_once_per_makerspace',
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='stripe', max_length=16),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='razorpay_key_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='razorpay_webhook_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], default='stripe', max_length=16),
        ),
        migrations.AddField(
            model_name='processedstripeevent',
            name='provider',
            field=models.CharField(default='stripe', max_length=16),
        ),
        migrations.RunPython(
            copy_stripe_ids_into_the_generic_columns,
            clear_the_generic_columns,
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_order_id__isnull', False)), fields=('provider', 'external_order_id'), name='payment_external_order_once_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_payment_id__isnull', False)), fields=('provider', 'external_payment_id'), name='payment_external_payment_once_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='processedstripeevent',
            constraint=models.UniqueConstraint(fields=('makerspace', 'provider', 'stripe_event_id'), name='webhook_event_once_per_makerspace_provider'),
        ),
    ]
