# Generated by Django 6.0.8 on 2026-09-03 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_allow_waived_online_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_deposit_blocks_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_deposit_mode',
            field=models.CharField(choices=[('none', 'No deposit'), ('fixed', 'Fixed amount per loan'), ('per_product', 'Sum of product deposits')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_grace_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_late_fee_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='makerspacepaymentsettings',
            name='loan_late_fee_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subject_type',
            field=models.CharField(choices=[('machine_service_request', 'Machine service request'), ('booking', 'Booking'), ('event_registration', 'Event registration'), ('makerspace_membership', 'Makerspace membership'), ('membership_term', 'Membership renewal'), ('loan_deposit', 'Loan deposit'), ('loan_late_fee', 'Loan late fee')], max_length=48),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Default currency must be a three-letter lowercase ISO currency code.', regex='^[a-z]{3}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], max_length=16)),
                ('external_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'), models.UniqueConstraint(condition=models.Q(('external_refund_id__isnull', False)), fields=('provider', 'external_refund_id'), name='refund_external_once_per_provider')],
            },
        ),
    ]
