# Generated by Django 6.0.8 on 2026-09-05 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Append-only at the DATABASE, not merely in the ORM. The whole reason this ledger is a
# separate table rather than four columns on `Payment` is that a receipt must not be
# quietly rewritten after the fact -- the payment terminal-guard only protects `status`
# and `amount`, so columns there would have been editable with nothing to show for it.
# Corrections are an appended `amends` row instead.
SETTLEMENT_GUARD_SQL = """CREATE OR REPLACE FUNCTION payments_manual_settlement_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    -- The lifecycle purge is the one legitimate eraser, exactly as for Payment itself.
    IF current_setting('app.allow_immutable_delete', true) = 'on' THEN RETURN OLD; END IF;
    RAISE EXCEPTION 'manual settlement is append-only';
  END IF;
  RAISE EXCEPTION 'manual settlement is append-only';
END; $$;"""

DROP_SETTLEMENT_GUARD_SQL = "DROP FUNCTION IF EXISTS payments_manual_settlement_guard() CASCADE;"

ATTACH_SQL = """DROP TRIGGER IF EXISTS payments_manual_settlement_guard ON payments_manualsettlement;
CREATE TRIGGER payments_manual_settlement_guard
BEFORE UPDATE OR DELETE ON payments_manualsettlement
FOR EACH ROW EXECUTE FUNCTION payments_manual_settlement_guard();"""

DETACH_SQL = "DROP TRIGGER IF EXISTS payments_manual_settlement_guard ON payments_manualsettlement;"


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_payment_unclaimed_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank transfer'), ('card_machine', 'Card machine'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Default currency must be a three-letter lowercase ISO currency code.', regex='^[a-z]{3}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amends', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amended_by', to='payments.manualsettlement')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_settlements', to='payments.payment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='manual_settlement_amount_positive')],
            },
        ),
        migrations.RunSQL(SETTLEMENT_GUARD_SQL, DROP_SETTLEMENT_GUARD_SQL),
        migrations.RunSQL(ATTACH_SQL, DETACH_SQL),
    ]
