# Generated by Django 6.0.8 on 2026-09-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_manual_settlement_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsettlement',
            name='amends',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amended_by', to='payments.manualsettlement'),
        ),
        migrations.AlterField(
            model_name='manualsettlement',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_settlements', to='payments.payment'),
        ),
    ]
