# Generated by Django 6.0.8 on 2026-08-16 03:23

import django.db.models.deletion
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0063_makerspacemembership_activated_actor_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('holder', models.UUIDField(blank=True, null=True)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_backups_enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('last_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('deployment', 'Full deployment'), ('makerspace', 'Makerspace')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('available', 'Available'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('age_encrypted', models.BooleanField(default=False)),
                ('failure_detail', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('download_token_digest', models.CharField(blank=True, max_length=64)),
                ('download_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_token_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_archives', to='makerspaces.makerspace')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_backup_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RestoreOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rollback_in_place', 'Rollback in place'), ('disaster', 'Disaster or cross-server')], max_length=24)),
                ('stage', models.CharField(choices=[('requested', 'Requested'), ('claimed', 'Claimed'), ('preflight', 'Preflight'), ('quiesced', 'Quiesced'), ('db_restoring', 'Database restoring'), ('objects_restoring', 'Objects restoring'), ('validating', 'Validating'), ('completed', 'Completed'), ('restored_quarantined', 'Restored quarantined'), ('rolling_back', 'Rolling back'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='requested', max_length=24)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('proceed', 'Proceed'), ('reset', 'Proceed with authority reset'), ('abort', 'Abort')], default='pending', max_length=16)),
                ('fencing_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('restore_diff', models.JSONField(blank=True, default=dict)),
                ('decision_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=500)),
                ('requested_by_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restores', to='backup.backuparchive')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_restores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='DeploymentRecoveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('quiesced', 'Quiesced'), ('quarantined', 'Quarantined')], default='normal', max_length=16)),
                ('auth_generation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_recovery_states', to=settings.AUTH_USER_MODEL)),
                ('recovery_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_principal_states', to=settings.AUTH_USER_MODEL)),
                ('active_restore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_states', to='backup.restoreoperation')),
            ],
        ),
        migrations.CreateModel(
            name='RestoreRollbackObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_kind', models.CharField(choices=[('private', 'Private'), ('public_image', 'Public image')], max_length=16)),
                ('module_key', models.CharField(blank=True, max_length=64)),
                ('source_key', models.CharField(max_length=1024)),
                ('copy_key', models.CharField(blank=True, max_length=1024)),
                ('source_was_absent', models.BooleanField(default=False)),
                ('source_version_id', models.CharField(blank=True, max_length=512)),
                ('replacement_version_id', models.CharField(blank=True, max_length=512)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('makerspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_rollback_objects', to='makerspaces.makerspace')),
                ('restore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_objects', to='backup.restoreoperation')),
            ],
        ),
        migrations.AddIndex(
            model_name='backuparchive',
            index=models.Index(fields=['scope', 'makerspace', 'status', 'created_at'], name='backup_back_scope_32ce8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='restorerollbackobject',
            constraint=models.UniqueConstraint(fields=('restore', 'bucket_kind', 'source_key'), name='uniq_restore_rollback_object'),
        ),
    ]
