# Generated by Django 6.0.8 on 2026-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuparchive',
            name='archive_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
