# Generated by Django 6.0.8 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_backuparchive_archive_sha256"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveRecipientReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("makerspace_id_snapshot", models.BigIntegerField(null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("tenant", "Tenant"), ("platform", "Platform")],
                        max_length=16,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("kind", "tenant"),
                                ("makerspace_id_snapshot__isnull", False),
                            )
                            | models.Q(
                                ("kind", "platform"),
                                ("makerspace_id_snapshot__isnull", True),
                            )
                        ),
                        name="archive_reservation_kind_matches_tenant",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="MakerspaceArchiveRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_recipient", models.CharField(max_length=200)),
                ("fingerprint", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=120)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("compromised_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("challenge_nonce_digest", models.CharField(blank=True, max_length=64)),
                ("challenge_issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_archive_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "makerspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_recipients",
                        to="makerspaces.makerspace",
                    ),
                ),
            ],
            options={"ordering": ("pk",)},
        ),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION backup_reject_reservation_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'append-only/immutable table: % not allowed', TG_OP;
END;
$$;

CREATE TRIGGER backup_archiverecipientreservation_no_update
BEFORE UPDATE ON backup_archiverecipientreservation
FOR EACH ROW EXECUTE FUNCTION backup_reject_reservation_mutation();

CREATE TRIGGER backup_archiverecipientreservation_no_delete
BEFORE DELETE ON backup_archiverecipientreservation
FOR EACH ROW EXECUTE FUNCTION backup_reject_reservation_mutation();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS backup_archiverecipientreservation_no_update
ON backup_archiverecipientreservation;
DROP TRIGGER IF EXISTS backup_archiverecipientreservation_no_delete
ON backup_archiverecipientreservation;
DROP FUNCTION IF EXISTS backup_reject_reservation_mutation();
""",
        ),
    ]
