# Generated by Django 6.0.8 on 2026-08-22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0007_backuparchive_decision_snapshot_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakerspaceArchiveCustodyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            (
                                "degraded_one_recipient",
                                "Degraded: one recipient",
                            ),
                            (
                                "floor_breached_zero",
                                "Floor breached: zero",
                            ),
                        ],
                        default="healthy",
                        max_length=32,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                (
                    "entered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("last_alarm_at", models.DateTimeField(blank=True, null=True)),
                ("alarm_episode", models.PositiveBigIntegerField(default=0)),
                (
                    "makerspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_custody_state",
                        to="makerspaces.makerspace",
                    ),
                ),
                (
                    "triggering_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_custody_states",
                        to="backup.makerspacearchiverecipient",
                    ),
                ),
            ],
        ),
    ]
