# Generated by Django 5.1.15 on 2026-07-19 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_file_makerspace(apps, schema_editor):
    ServiceRequestFile = apps.get_model("machines", "ServiceRequestFile")
    for file_id, makerspace_id in ServiceRequestFile.objects.filter(
        makerspace__isnull=True
    ).values_list("id", "machine__makerspace_id"):
        ServiceRequestFile.objects.filter(pk=file_id).update(makerspace_id=makerspace_id)


def backfill_request_makerspace(apps, schema_editor):
    Request = apps.get_model("machines", "MachineServiceRequest")
    for request_id, bucket_space, queue_space in Request.objects.filter(makerspace__isnull=True).values_list(
        "id", "bucket__machine__makerspace_id", "queue__makerspace_id"
    ):
        Request.objects.filter(pk=request_id).update(makerspace_id=bucket_space or queue_space)


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_member_service_request_owner'),
        ('makerspaces', '0045_membership_join_policy_referrals'),
        # This migration REPLACES the pii_fence_machine_service_request function that
        # encryption/0006 creates, swapping its bucket-join lookup for NEW.makerspace_id
        # once that column exists. Both migrations previously depended only on
        # machines/0010, so they were siblings and Django ordered them arbitrarily -- it
        # happened to pick the right order until a new cross-app dependency elsewhere
        # perturbed the traversal, and then encryption/0006's plain CREATE FUNCTION
        # aborted the whole build with DuplicateFunction.
        #
        # Making that CREATE idempotent would be the WRONG fix: it would then overwrite
        # this migration's newer body with the stale bucket-join one, silently reverting
        # a PII write fence to logic that reads a column this migration moved. The
        # ordering is a real requirement, so it is declared here instead.
        ('encryption', '0006_machine_service_request_pii_fence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConsumableAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reserve', 'Reserve'), ('reconcile', 'Reconcile'), ('manual', 'Manual'), ('correction', 'Correction'), ('retire', 'Retire')], max_length=16)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MachineConsumablePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('lot_code', models.CharField(blank=True, max_length=100)),
                ('initial_grams', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_grams', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_threshold_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('allocation_policy', models.CharField(choices=[('first_idle', 'First compatible idle machine'), ('staff_select', 'Staff selects machine')], default='staff_select', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['makerspace__name', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='machineusageentry',
            name='machineusage_hours_positive',
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='makerspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_service_requests', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='actual_consumed_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='capability_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='payment_status',
            field=models.CharField(default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='planned_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='reprint_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprints', to='machines.machineservicerequest'),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='reserved_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_consumable_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_consumable_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_consumable_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_estimated_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_machine_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_machine_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_planned_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='machinetype',
            name='capability_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='consumed_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='percent_complete',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_entries', to='machines.machineservicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestfile',
            name='makerspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_request_files', to='makerspaces.makerspace'),
        ),
        migrations.RunPython(backfill_file_makerspace, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicerequestfile',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_request_files', to='makerspaces.makerspace'),
        ),
        migrations.AlterField(
            model_name='machineservicerequest',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='machines.servicebucket'),
        ),
        migrations.AlterField(
            model_name='machineusageentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machineusageentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual hours'), ('typed_manual', 'Typed manual service')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='servicerequestfile',
            name='kind',
            field=models.CharField(choices=[('attachment', 'Attachment'), ('model', 'Model'), ('estimate', 'Estimate'), ('preview', 'Preview'), ('screenshot', 'Screenshot')], max_length=16),
        ),
        migrations.AlterField(
            model_name='servicerequestfile',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_files', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machineconsumableadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineconsumableadjustment',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_consumable_adjustments', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='machineconsumableadjustment',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_adjustments', to='machines.machineservicerequest'),
        ),
        migrations.AddField(
            model_name='machineconsumableadjustment',
            name='usage_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_adjustments', to='machines.machineusageentry'),
        ),
        migrations.AddField(
            model_name='machineconsumablepool',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineconsumablepool',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_pools', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machineconsumablepool',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_consumable_pools', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='machineconsumableadjustment',
            name='consumable_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='machines.machineconsumablepool'),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='run_consumable_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_service_requests', to='machines.machineconsumablepool'),
        ),
        migrations.AddField(
            model_name='machineusageentry',
            name='consumable_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_entries', to='machines.machineconsumablepool'),
        ),
        migrations.AddConstraint(
            model_name='machineusageentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gte', 0)), name='machineusage_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineusageentry',
            constraint=models.CheckConstraint(condition=models.Q(('percent_complete__gte', 0), ('percent_complete__lte', 100)), name='machineusage_percent_complete_range'),
        ),
        migrations.AddConstraint(
            model_name='machineusageentry',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_grams__gte', 0)), name='machineusage_grams_nonnegative'),
        ),
        migrations.AddField(
            model_name='servicequeue',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_queues', to='machines.machinetype'),
        ),
        migrations.AddField(
            model_name='servicequeue',
            name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_queues', to='makerspaces.makerspace'),
        ),
        migrations.AddField(
            model_name='machineservicerequest',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='machines.servicequeue'),
        ),
        migrations.AddField(
            model_name='servicerequestfile',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_files', to='machines.servicequeue'),
        ),
        migrations.RunPython(backfill_request_makerspace, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='machineservicerequest', name='makerspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_service_requests', to='makerspaces.makerspace'),
        ),
        migrations.AddIndex(
            model_name='machineservicerequest',
            index=models.Index(fields=['queue', 'status', '-created_at'], name='servicereq_queue_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bucket__isnull', False), ('queue__isnull', True)), models.Q(('bucket__isnull', True), ('queue__isnull', False)), _connector='OR'), name='service_req_bucket_xor_queue'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('planned_grams__gte', 0)), name='service_req_planned_grams_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_grams__gte', 0)), name='service_req_reserved_grams_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineservicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('actual_consumed_grams__gte', 0)), name='service_req_actual_grams_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='machineconsumablepool',
            index=models.Index(fields=['makerspace', 'is_active'], name='consumable_pool_scope_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='machineconsumablepool',
            constraint=models.CheckConstraint(condition=models.Q(('initial_grams__gte', 0)), name='consumable_pool_initial_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='machineconsumablepool',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_grams__gte', 0), ('remaining_grams__lte', models.F('initial_grams'))), name='consumable_pool_balance_capped'),
        ),
        migrations.AddConstraint(
            model_name='machineconsumableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='consumable_adjustment_nonzero'),
        ),
        migrations.AddIndex(
            model_name='servicequeue',
            index=models.Index(fields=['makerspace', 'machine_type', 'is_active'], name='service_queue_scope_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicequeue',
            constraint=models.UniqueConstraint(fields=('makerspace', 'name'), name='uniq_service_queue_makerspace_name'),
        ),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION machine_kernel_reject_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.allow_immutable_delete', true) = 'on' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'append-only/immutable table: % not allowed', TG_OP;
END;
$$;
CREATE TRIGGER machine_consumable_adjustment_no_update BEFORE UPDATE ON machines_machineconsumableadjustment FOR EACH ROW EXECUTE FUNCTION machine_kernel_reject_mutation();
CREATE TRIGGER machine_consumable_adjustment_no_delete BEFORE DELETE ON machines_machineconsumableadjustment FOR EACH ROW EXECUTE FUNCTION machine_kernel_reject_mutation();
CREATE TRIGGER machine_usage_entry_no_update BEFORE UPDATE ON machines_machineusageentry FOR EACH ROW EXECUTE FUNCTION machine_kernel_reject_mutation();
CREATE TRIGGER machine_usage_entry_no_delete BEFORE DELETE ON machines_machineusageentry FOR EACH ROW EXECUTE FUNCTION machine_kernel_reject_mutation();
""",
            reverse_sql="""
DROP TRIGGER IF EXISTS machine_consumable_adjustment_no_update ON machines_machineconsumableadjustment;
DROP TRIGGER IF EXISTS machine_consumable_adjustment_no_delete ON machines_machineconsumableadjustment;
DROP TRIGGER IF EXISTS machine_usage_entry_no_update ON machines_machineusageentry;
DROP TRIGGER IF EXISTS machine_usage_entry_no_delete ON machines_machineusageentry;
DROP FUNCTION IF EXISTS machine_kernel_reject_mutation();
""",
        ),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION pii_fence_machine_service_request() RETURNS trigger AS $$
BEGIN
  PERFORM pii_assert_mapped_write_allowed(NEW.makerspace_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""",
            reverse_sql="""
CREATE OR REPLACE FUNCTION pii_fence_machine_service_request() RETURNS trigger AS $$
DECLARE tenant_id bigint;
BEGIN
  SELECT machine.makerspace_id INTO tenant_id
  FROM machines_servicebucket bucket
  JOIN machines_machine machine ON machine.id = bucket.machine_id
  WHERE bucket.id = NEW.bucket_id
  FOR KEY SHARE OF bucket, machine;
  PERFORM pii_assert_mapped_write_allowed(tenant_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
""",
        ),
    ]
