# Generated by Django 6.0.8 on 2026-08-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_makerspace_machine_type_pricing'),
        ('makerspaces', '0054_alter_makerspacemembership_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMachineScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_scopes', to='machines.machine')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_scopes', to='makerspaces.makerspacerole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'machine'), name='rolemachinescope_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RoleMachineTypeScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_scopes', to='machines.machinetype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_type_scopes', to='makerspaces.makerspacerole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'machine_type'), name='rolemachinetypescope_uniq')],
            },
        ),
    ]
