# Generated by Django 6.0.8 on 2026-09-03 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0023_machine_search_vector'),
        ('makerspaces', '0067_reconcile_anonymous_requests_with_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_required_for_service', models.BooleanField(default=False)),
                ('is_required_for_booking', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_types', to='machines.machinetype')),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_types', to='makerspaces.makerspace')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_granted', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_grants', to='makerspaces.makerspacemembership')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_revoked', to=settings.AUTH_USER_MODEL)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='machines.certificationtype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='certificationtype',
            constraint=models.UniqueConstraint(fields=('makerspace', 'machine_type', 'name'), name='certificationtype_uniq_name'),
        ),
        migrations.AddIndex(
            model_name='certificationgrant',
            index=models.Index(fields=['membership', 'certification_type'], name='certgrant_member_type_idx'),
        ),
    ]
